name: exo3
on: 
  pull_request:
    types:
     - closed 
    branches:
     - master 
env:
   APP_VERSION: "1.0.0" # avec docker, les versions c'est en chaine de caractere et non des chiffres.
jobs: 

  Tests-exo3: 
    runs-on: ubuntu-latest
    steps: 
      - name: recuperation du Repository12 
        uses: actions/checkout@v3
      - name: Installation des dépendances
        run: pip install -r requirements.txt
      - name: lancement des requirements.txt
        run: pytest 
      
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - run: python my_script.py

      - name: Execution des tests unitaires
        run: npm test
      - name: Execution du code coverage
        run: npm run cover
      - name: Récuperation du rapport 
        uses: actions/upload-artifact@v3
        with:
          name: intro-to-pytest
          path: ./into-to-pytest/**

  Build-app:
    needs: Tests-exo3
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du repository
        uses: actions/checkout@v3
      - name: Installation de QEMU
        uses: docker/setup-qemu-action@v1
      - name: Installation de Docker Buildx 
        uses: docker/setup-buildx-action@v1
      - name: Login au docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & push docker
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/img2:${{ env.APP_VERSION }}
